Repository googleapis/nodejs-dns, pull requests merged in 2019-05, with the labels that each got.

#244 docs(samples): modernize the samples, tests, and README
  .cloud-repo-tools.json
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/.eslintrc.yml
  samples/README.md
  samples/listZones.js
  samples/package.json
  samples/quickstart.js
  samples/system-test/quickstart.test.js
  samples/test/.eslintrc.yml
  samples/test/dns.test.js
  src/index.ts
  src/zone.ts
  synth.metadata
Labels: cla: yes

#245 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#246 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#247 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#252 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#254 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#253 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#251 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#260 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#264 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#265 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#268 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#267 chore: release 1.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#270 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#271 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#272 feat: support apiEndpoint overrides
  package.json
  src/index.ts
  test/index.ts
Labels: cla: yes
