Repository googleapis/nodejs-dns, pull requests merged in 2020-06, with the labels that each got.

#394 chore(deps): update dependency @types/tmp to v0.2.0
  package.json
  system-test/dns.ts
Labels: cla: yes

#395 build: update secrets configuration
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: none

#397 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#398 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#399 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
