Repository googleapis/nodejs-dns, pull requests merged in 2021-05, with the labels that each got.

#449 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: dns, cla: yes, context: full

#451 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#452 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: dns, automerge, cla: yes, context: full

#455 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  synth.metadata
  synth.py
Labels: api: dns, cla: yes
